### ISSUE TITLE
org.eclipse.swt.SWTException: Unspecified error thrown when Restoring Defaults in Preference Page

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#276] opened 2019-04-11 08:21 UTC
**Describe the bug**
A CogniCrypt user reported the following exception:

>I tested the new CogniCrypt version: {{1.0.0.201903291356}} with a new
eclipse version {{2018-12 (4.10.0)}}, java version {{1.8.0_162}} and
could identify following: If I press the button _Restore Defaults_, following exception is
> logged sometimes, but not every time:

```
{panel:title=Unhandled event loop exception}
org.eclipse.swt.SWTException: Unspecified error
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at
java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
 at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
 at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
 at
java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
 at
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
 at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
 at
java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
 at
de.cognicrypt.core.properties.CogniCryptPreferencePage.setDefaultValues(CogniCryptPreferencePage.java:82)
 at
de.cognicrypt.core.properties.CogniCryptPreferencePage.performDefaults(CogniCryptPreferencePage.java:66)
 at
org.eclipse.jface.preference.PreferencePage.lambda$0(PreferencePage.java:277)
 at
org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
 at
org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
 at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
 at org.eclipse.jface.window.Window.open(Window.java:798)
 at
org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:214)
 at
org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
 at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
 at
org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
 at
org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
 at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
 at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
 at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
 at
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
 at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
 at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
 at
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
 at
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
 at
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
 at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
 at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
 at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
 at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
 at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
{panel}
```

I could not reproduce the bug on my machine.

**Comment by johspaeth** [comment] 2019-04-11 08:22
@shahrzadav Could you please research on what may cause the problem?

**Comment by shahrzadav** [comment] 2019-04-11 08:33
@johspaeth yeah sure.

**Comment by shahrzadav** [comment] 2019-04-21 10:06
unfortunately I could not reproduce the error, with the same version of java, eclipse and windows. it also can be eclipses error. maybe it helps if we have more concrete information on how it can get reproduced.

**Comment by kruegers** [comment] 2019-05-09 10:39
Closing this issue for now until it occurs again and we can gain more information about how it can be reproduced.

**Closed as completed by kruegers** 2019-05-09 10:39 UTC
Labels: bug, UI-related
