### ISSUE TITLE
java.util.concurrent.CancellationException when creating markers

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#275] opened 2019-04-11 08:14 UTC
**Describe the bug**
A user of CogniCrypt reported the following:

> 
> I tested the new CogniCrypt version: {{1.0.0.201903291356}} with a new
> eclipse version {{2018-12 (4.10.0)}}, java version {{1.8.0_162}} and
> could identify following:
> I selected a single Eclipse Plug-in and click on toolbar item: _Apply
> CogniCrypt Misuse Detection to Selected Project_, the following
> exception is logged multiple times:

```
{panel:title=Problems occurred when invoking code from plug-in:
"org.eclipse.jface".}
java.util.concurrent.CancellationException
 at
java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
 at
org.eclipse.ui.internal.navigator.resources.nested.NestedProjectsLabelProvider.lambda$1(NestedProjectsLabelProvider.java:69)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
 at
org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
 at
org.eclipse.ui.internal.navigator.resources.nested.NestedProjectsLabelProvider.lambda$0(NestedProjectsLabelProvider.java:64)
 at
org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
 at
org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
 at
org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
 at
org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
 at
org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
 at
org.eclipse.core.internal.resources.Resource.createMarker(Resource.java:696)
 at
de.cognicrypt.staticanalyzer.results.ErrorMarkerGenerator.addMarker(ErrorMarkerGenerator.java:60)
 at
de.cognicrypt.staticanalyzer.results.ResultsCCUIListener.reportError(ResultsCCUIListener.java:175)
 at
crypto.analysis.CrySLResultsReporter.reportError(CrySLResultsReporter.java:153)
 at
crypto.predicates.PredicateHandler.checkMissingRequiredPredicates(PredicateHandler.java:220)
 at
crypto.predicates.PredicateHandler.checkPredicates(PredicateHandler.java:208)
 at crypto.analysis.CryptoScanner.scan(CryptoScanner.java:97)
 at
de.cognicrypt.staticanalyzer.sootbridge.SootRunner$1.internalTransform(SootRunner.java:77)
 at soot.SceneTransformer.transform(SceneTransformer.java:36)
 at soot.Transform.apply(Transform.java:102)
 at soot.ScenePack.internalApply(ScenePack.java:35)
 at soot.Pack.apply(Pack.java:117)
 at
de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:128)
 at
de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:116)
 at de.cognicrypt.staticanalyzer.handlers.SootThread.run(SootThread.java:23)
{panel}
```

Could be related to this bug:
https://github.com/angelozerr/jdt-codemining/issues/83

It was reported on a Windows 10 machine. But I do not have more information about the project etc. I also could not yet reproduce the bug.

**Comment by kruegers** [comment] 2019-04-18 11:22
assigned @AndreSonntag.

**Comment by AndreSonntag** [comment] 2019-04-28 10:14
First of all, I was not able to reproduce the bug. I created a normal plugin project and started the analysis for it, but the error doesn't appeared.

**I'm not sure**, but I think it is a eclipse platform related bug. I read several eclipse reports on bugs.eclipse.org about the CancellationException exception and the reason could be a too deep project hierarchy of a plugin.  

https://bugs.eclipse.org/bugs/show_bug.cgi?id=542946

**Comment by kruegers** [comment] 2019-05-09 10:41
Closing this issue for now. If it is related to Eclipse, we cannot fix it anyway. Should it indeed be caused by CogniCrypt, we'd need more details to reproduce it. One should feel free to re-open the issue when they can provide more concrete steps for reproducing the bug.

**Closed as completed by kruegers** 2019-05-09 10:41 UTC
Labels: bug, UI-related, SAST
